params:
  website_contributing_branch: dev

module:
  mounts:
  - source: content/api/src/R_Project_UltimateXR.md
    target: content/api/_index.md
  - source: content/api/src
    target: content/api
  - source: content/api/src/media
    target: assets/media/api
  - source: assets
    target: assets
  - source: content
    target: content
    excludeFiles: ['api/src', 'api/src/media']